### PR TITLE
Jumpstart lab

### PR DESCRIPTION
**Pull request by kbrownell**
It looks like I waited too long before submitting a pull request.  However, these install tasks should pull in relevant content and set up the scaffolding of a JSLab Menu and Home Page layout.  Surely, there are areas for improvement in here.

### CODE REVIEW

**Comment by kbrownell** [comment]
I noticed that a number of the blocks are prefaced with jumpstart, for example jumpstart-homepage-research-projects or jumsptart-footer-logo-block.  Please let me know if I should rename these two new blocks in keeping with that naming convention.

Also, I was able to add a header background image to the Stanford Framework theme through the GUI.  But am still looking for options to save those settings in code.  The DrupalCamp install tasks has a ThemeSettings.php file that looks like a promising example.

**Comment by kbrownell** [comment]
1. Rename jumpstart-lab-homepage-research-projects and jumsptart-lab-footer-logo-blocks.
2. Upload header file to jsa-content.  Import the file, try: process_field_file_create_item($uuid) from stanford_sites_content_importer/ImporterFieldProcessorFile.php.  And then add it to customized design in HomepageSettings.php.  Once I get the file_id after import, I should be able to add it to the sjh_stanford_jumpstart_mayfield_lab with variable_get/set. ie. stanford_jumpstart_homepage_dashboard_form_submit($form, $form_state) $config['header_image'] needs the file_id.
3. Compare permissions from HSLab to JSL and export a feature for the permissions as a custom module: jumpstart_lab_permissions.  Ideally, would enable the module last as part of install tasks.

**Comment by kbrownell** [comment]
Error message related to ceb74bc:

```
Fatal error: Class 'Stanford\JumpstartLab\Install\ImporterFieldProcessorFile' not found in /Users/[USERNAME]/Sites/sws-build-jsl/sites/all/libraries/tasks/Stanford/JumpstartLab/Install/HomePageSettings.php on line 50
Drush command terminated abnormally due to an unrecoverable error.                                                                [error]
Error: Class 'Stanford\JumpstartLab\Install\ImporterFieldProcessorFile' not found in
/Users/[USERNAME]/Sites/sws-build-jsl/sites/all/libraries/tasks/Stanford/JumpstartLab/Install/HomePageSettings.php, line 50
```

**Comment by sherakama** [comment]
Jumpstart Academic calls this task to load the libraries: https://github.com/SU-SWS/stanford_sites_jumpstart_academic/blob/7.x-5.x/stanford_sites_jumpstart_academic.info#L37

You probably want to do the same before trying to use the ImporterFieldProcessorFile.

When you create a new class you will probably have to prefix it with the global namespace

eg: `new \ImporterFieldProcessorFile();`

**Comment by kbrownell** [comment]
Hello Shea.  It looks like I am already calling this task: https://github.com/SU-SWS/stanford_sites_jumpstart_lab/blob/7.x-5.x/stanford_sites_jumpstart_lab.info#L37.  Let me know if that should do the trick.

I'm not entirely sure what you mean by prefixing with the global namespace, but when I add a backslash to \ImporterFieldProcessorFile(); I get the following error message:

```
exception 'Exception' with message 'Could not fetch file:                           [error]
3331b480-51bd-4086-bafc-6b5cd342c410' in
/Users/kelliebrownell/Sites/sws-build-jsl/sites/all/libraries/stanford_sites_content_importer/ImporterFieldProcessorFile.php:113
Stack trace:
#0
/Users/kelliebrownell/Sites/sws-build-jsl/sites/all/libraries/tasks/Stanford/JumpstartLab/Install/HomePageSettings.php(49):
ImporterFieldProcessorFile->process_field_file_create_item('3331b480-51bd-4...')
#1
/Users/kelliebrownell/Sites/sws-build-jsl/profiles/stanford_sites_jumpstart_lab/includes/iTasks.php(215):
Stanford\JumpstartLab\Install\HomePageSettings->execute(Array)
#2 /Users/kelliebrownell/Sites/sws-build-jsl/includes/install.core.inc(471):
itask_run_install_task(Array)
#3 /Users/kelliebrownell/Sites/sws-build-jsl/includes/install.core.inc(339):
install_run_task(Array, Array)
#4 /Users/kelliebrownell/Sites/sws-build-jsl/includes/install.core.inc(77):
install_run_tasks(Array)
#5 /usr/local/Cellar/drush/8.1.3/libexec/includes/drush.inc(725):
install_drupal(Array)
#6 /usr/local/Cellar/drush/8.1.3/libexec/includes/drush.inc(711):
drush_call_user_func_array('install_drupal', Array)
#7
/usr/local/Cellar/drush/8.1.3/libexec/commands/core/drupal/site_install_7.inc(82):
drush_op('install_drupal', Array)
#8 /usr/local/Cellar/drush/8.1.3/libexec/commands/core/site_install.drush.inc(247):
drush_core_site_install_version('stanford_sites_...', Array)
#9 [internal function]: drush_core_site_install('stanford_sites_...')
#10 /usr/local/Cellar/drush/8.1.3/libexec/includes/command.inc(373):
call_user_func_array('drush_core_site...', Array)
#11 /usr/local/Cellar/drush/8.1.3/libexec/includes/command.inc(224):
_drush_invoke_hooks(Array, Array)
#12 [internal function]: drush_command('stanford_sites_...')
#13 /usr/local/Cellar/drush/8.1.3/libexec/includes/command.inc(192):
call_user_func_array('drush_command', Array)
#14 /usr/local/Cellar/drush/8.1.3/libexec/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#15 /usr/local/Cellar/drush/8.1.3/libexec/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#16 /usr/local/Cellar/drush/8.1.3/libexec/drush.php(12): drush_main()
#17 {main}
```

Here is a screenshot of the UUID, in the event I might accidentally be using the wrong one.  I have also cleared cache on jsa-content as well.

screen shot 2016-10-24 at 1 06 29 pm

**Comment by sherakama** [comment]
That file appears to be there: https://sites.stanford.edu/jsa-content/jsainstall/file/3331b480-51bd-4086-bafc-6b5cd342c410.json

I am getting the same error on a build. 
To the debugger!

**Comment by sherakama** [comment]
@kbrownell,

Looks like it was missing the endpoint configuration and was requesting to localhost. See changes: https://github.com/SU-SWS/stanford_install_tasks/pull/34/commits/9982684b719e5fb24f3737287a14dcfa80a827ee

**Comment by sherakama** [comment]
That file appears to be there: https://sites.stanford.edu/jsa-content/jsainstall/file/3331b480-51bd-4086-bafc-6b5cd342c410.json <https://sites.stanford.edu/jsa-content/jsainstall/file/3331b480-51bd-4086-bafc-6b5cd342c410.json>

Looking at the code it would appear that the importer did not receive a valid response from jsa-content. Maybe it was cached somewhere else or there was a network issue at the time. 

https://github.com/SU-SWS/stanford_sites_content_importer/blob/7.x-1.x/ImporterFieldProcessorFile.php#L110 <https://github.com/SU-SWS/stanford_sites_content_importer/blob/7.x-1.x/ImporterFieldProcessorFile.php#L110>

Can you try again and or push up some code for me to test with?

-Shea

**Comment by kbrownell** [comment]
It appears that the file is now being imported, however, I have not succeeded in setting the background image.  I tried re-arranging the order in which the install tasks are run, ie. putting HomepageSettings before ThemeSettings, without success: https://github.com/SU-SWS/stanford_sites_jumpstart_lab/commit/e2fcdd8949cf95d3d9c4a1d44edb813ef032b372.  And am happy to keep trying to understand how variables are getting assigned/set.  But if you have any quick tips in the interim, let me know!  Latest attempt: https://github.com/SU-SWS/stanford_install_tasks/pull/34/commits/ec7179cbb78beba723947340e7a69cd67ee7ef21.

Also note: I was previously importing the node on which I have uploaded the header image in jsa-content (node/10510).  But when I imported node/10510 AND then in HomepageSettings tried to create the file, it said duplicate found in database and failed to build.  So now, I am not importing node/10510.

**Pull request merged**
